version: "3.9"
services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-framework-webserver
    container_name: php-framework-webserver
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - ${APACHE_PORT}:80
    networks:
      - php-framework

  mysql:
    image: mysql:latest
    container_name: php-framework-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - php-framework

networks:
  php-framework:
    driver: bridge